### ISSUE TITLE
Feature: Cut probes based on interpolated neighbors/Black color

### ISSUE THREAD

**Issue by BlueAmulet** [SpockBauru/ProbeGridAndCut#1]
Just a couple of ideas for probe reduction:

Removing probes based on if the probe's color, is similar enough to a mix between its up/down, left/right, forward/back neighbors.

Removing probes if all six directions of the probe are near black, could be great for removing probes that are inside of objects that don't get caught by the existing inside object cut. Obviously there may be times where a scene is intentionally not well lit and the probe is supposed to be black, so this would definitely have to be optional.

**Comment by SpockBauru** [comment]
Wow, someone besides me is using the tool! Thanks ^-^
I mean, the Asset Store reports that only 26 people downloaded since v2.0 launch... 

About the feature, seems doable with a bit of work. I will take a look when I have some time to spare, but given how low the userbase is it will not be a priority, unfortunately...
